target-version = "py312"
line-length = 100
show-fixes = true

[lint]
select = ["ALL"]
ignore = [
    "D100","D101","D102","D103","D104","D105","D106","D107",
    "CPY001",
    "ANN003", "ANN002",
    "TID252",
    "FIX", "TD",
    "RET504",
    "PLC0414",
    "D203","D213",
    "COM812",
    "FBT",
    "DOC502",
]
preview = true
# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    ".idea",
]
[lint.per-file-ignores]
"**/tests/*" = [
    "S101",
    "ANN201",
    "PLR2004",
    "PLC0415",
    "ANN205",
    "ANN201",
    "PLR6301",
]
